#Quelle:
# https://github.com/SilvrrGIT/HomeAssistant/blob/master/ui-lovelace.yaml
####################################################
#                                                  #
#                   VIEWS                          #
#                                                  #
####################################################

title: My Awesome Home
views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/lichter.yaml
  - !include lovelace/views/heizung.yaml
  - !include lovelace/views/wetter.yaml
  - !include lovelace/views/fuel.yaml
  - !include lovelace/views/table.yaml
  - !include lovelace/views/battery.yaml
  - !include lovelace/views/solar.yaml
  - !include lovelace/views/test.yaml
  - !include lovelace/views/test2.yaml
  - !include lovelace/views/aqara.yaml
  - !include lovelace/views/alexa.yaml
  - !include lovelace/views/links.yaml
  - !include lovelace/views/hmip.yaml
  - !include lovelace/views/synology.yaml


####################################################
#                                                  #
#                   RESSOURCES                     #
# stehen jetzt (03/2020) in der configuration.yaml #
####################################################
# https://github.com/kalkih/mini-media-player
# https://github.com/kalkih/mini-graph-card

