esphome:
  name: example
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-password

web_server:
  port: 80
  
logger:

# Enable Home Assistant API
api:
  password: !secret api-password
  
# Ein Passwort für Over The Air flashen  
ota:
  password: !secret ota-password

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time
    
# text sensor with general information
text_sensor:
  - platform: wifi_info
    ip_address:
      name: esphome_example_ip
    ssid:
      name: esphome_example_ssid
    bssid:
      name: esphome_example_bssid

# einschalten des Bluetooth scanning für den MH-ET Live ESP32
esp32_ble_tracker:
 
binary_sensor:
  - platform: ble_presence
    mac_address: 54:99:63:D9:18:4F
    name: "ESP32 BLE Tracker iPhone8Plus"
    
sensor:
  # WiFi Signal sensor
  - platform: wifi_signal
    name: esphome_example_wifi_signal
    update_interval: 60s

 # - platform: bluetooth_signal
 #   mac_address: 6c:c3:74:fe:d9:76
 #   name: esphome_was
    
switch:
  # Switch to restart the plug
  - platform: restart
    name: esphome_example_restart



