esphome:
  name: keller2
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Keller2 Fallback Hotspot"
    password: !secret fallback-pw

captive_portal:

# Enable logging
logger:

web_server:
  port: 80

# Enable Home Assistant API
api:
  password: !secret api-password

ota:
  password: !secret ota-password

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time
    
# text sensor with general information
text_sensor:
  - platform: wifi_info
    ip_address:
      name: esphome_keller2_ip
    ssid:
      name: esphome_keller2_ssid
    bssid:
      name: esphome_keller2_bssid

# DHT-Sensor     
sensor:
  - platform: dht
    pin: D2
    model: DHT22
    temperature:
      name: "Keller2 Temperature"
      filters:
        - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 0.0 -> 0.0
          - 19.5 -> 19.0
    humidity:
      name: "Keller2 Humidity"
      accuracy_decimals: 1
      filters:
        - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 0.0 -> 0.0
          - 56.0 -> 51.7
    update_interval: 30s

  # WiFi Signal sensor
  - platform: wifi_signal
    name: esphome_keller2_wifi_signal
    update_interval: 60s
    
switch:
  # Switch to restart the plug
  - platform: restart
    name: esphome_keller2_restart