esphome:
  name: keller
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Keller Fallback Hotspot"
    password: "puiNJaflBlYB"

captive_portal:

# Enable logging
logger:

web_server:
  port: 80
  
# Enable Home Assistant API
api:
  password: !secret api-password
  
ota:
  password: !secret ota-password

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time
    
# text sensor with general information
text_sensor:
  - platform: wifi_info
    ip_address:
      name: esphome_keller_ip
    ssid:
      name: esphome_keller_ssid
    bssid:
      name: esphome_keller_bssid

# DHT-Sensor     
sensor:
  - platform: dht
    pin: D1
    model: DHT22
    temperature:
      name: "Keller Temperature"
    humidity:
      name: "Keller Humidity"
    update_interval: 20s
    
  # WiFi Signal sensor
  - platform: wifi_signal
    name: esphome_keller_wifi_signal
    update_interval: 60s
    
switch:
  # Switch to restart the plug
  - platform: restart
    name: esphome_keller_restart