esphome:
  name: tempaz
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi-ssid
  password: !secret wifi-password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tempaz Fallback Hotspot"
    password: "9lGdt19hFjfF"
    
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api-password
  
web_server:
  port: 80
  
ota:
  password: !secret ota-password

sensor:
  - platform: dht
    pin: D2
    model: DHT22
    temperature:
      name: "D1mini Temperature"
        # ...
    humidity:
      name: "D1mini Humidity"
      
#  - platform: wifi_signal
 #   name: D1mini WiFi
  #  update_intervall: 10s